### PR TITLE
Deleting archives is now happening in one call to tarsnap for faster deletions

### PR DESCRIPTION
**Pull request by psde**
Deletion of archives can be faster when deleting all archives at once, see http://www.tarsnap.com/tips.html#faster-delete

### CODE REVIEW

**Comment by miracle2k** [comment]
That's a good idea, but I don't like the way the output changed here - it's supposed to be obvious in cron emails what happened. For this reason:

- Everything action was on it's own line.
- The "Keeping" log used to be a "debug" level, so that in standard mode, you see more clearly what is being deleted.

This new format has some properties that are good (deleted and kept archives are now longer intermixed in the output), but I still question the usefulness of listing potentially a hundred kept archives, when the delete action is really the relevant part.

**Comment by psde** [comment]
You are right, listing all kept archives by default is not useful. I updated the PR.

Maybe we can get away with listing all deleted archives in one line when we sort them?

**Comment by psde** [comment]
I added sorting to the output and noticed that printing the current job would be quite helpful, as most of the time no archive is going to be deleted. What do you think?

**Comment by miracle2k** [comment]
Great, thanks.

I think you're right, listing the current job might be useful.

**Comment by miracle2k** [comment]
About the current job, my cron output looks like this:

    Creating backup vdata: vdata-20140816-023002
    18 backups are matching 
    0 of those can be deleted

That is, I get the information, because a backup is created. This might not be the case if you are only running the "expire" command.

**Pull request merged**
